"""Add in Hue bridge info

Revision ID: 258d289a169a
Revises: b6637f24d0e0
Create Date: 2016-12-04 10:25:10.087095

"""

# revision identifiers, used by Alembic.
revision = '258d289a169a'
down_revision = 'b6637f24d0e0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HueBridges',
    sa.Column('bridge_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('user', sa.VARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('bridge_id'),
    sa.UniqueConstraint('user')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HueBridges')
    ### end Alembic commands ###
