"""Create password table and default Admin user

Revision ID: 29550a33fdc0
Revises: 40a8e554796c
Create Date: 2016-11-14 09:40:39.726913

"""

# revision identifiers, used by Alembic.
revision = '29550a33fdc0'
down_revision = '40a8e554796c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from hsdb import User
from hsdb import Password
from argon2 import argon2_hash

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Passwords',
    sa.Column('password_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('hashed_password', sa.BINARY(length=128), nullable=False),
    sa.PrimaryKeyConstraint('password_id')
    )
    op.create_index(op.f('ix_Passwords_hashed_password'), 'Passwords', ['hashed_password'], unique=False)
    op.add_column(u'Users', sa.Column('password_salt', sa.BINARY(length=32), nullable=False))
    op.create_index(op.f('ix_Users_password_salt'), 'Users', ['password_salt'], unique=False)
    ### end Alembic commands ###

    # Create our admin/admin user
    session = User._session
    u = User.insert(username='admin')
    session.commit()
    session.flush()
    p = Password.insert(hashed_password=bytearray(argon2_hash("admin", u.password_salt, t=2000, m=1024)))
    session.commit()



def downgrade():

    # Drop our admin user
    User.filter_by(username='admin').first().delete()

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_password_salt'), table_name='Users')
    op.drop_column(u'Users', 'password_salt')
    op.drop_index(op.f('ix_Passwords_hashed_password'), table_name='Passwords')
    op.drop_table('Passwords')
    ### end Alembic commands ###
