"""Add in password table

Revision ID: 29550a33fdc0
Revises: 40a8e554796c
Create Date: 2016-11-14 09:40:39.726913

"""

# revision identifiers, used by Alembic.
revision = '29550a33fdc0'
down_revision = '40a8e554796c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Passwords',
    sa.Column('password_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('hashed_password', sa.BINARY(length=32), nullable=False),
    sa.PrimaryKeyConstraint('password_id')
    )
    op.create_index(op.f('ix_Passwords_hashed_password'), 'Passwords', ['hashed_password'], unique=False)
    op.add_column(u'Users', sa.Column('password_salt', sa.BINARY(length=32), nullable=False))
    op.create_index(op.f('ix_Users_password_salt'), 'Users', ['password_salt'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_password_salt'), table_name='Users')
    op.drop_column(u'Users', 'password_salt')
    op.drop_index(op.f('ix_Passwords_hashed_password'), table_name='Passwords')
    op.drop_table('Passwords')
    ### end Alembic commands ###
