"""Add in relational mappings for flask-principal easy of use

Revision ID: 40a8e554796c
Revises: e1e967f56f02
Create Date: 2016-11-12 11:57:34.832344

"""

# revision identifiers, used by Alembic.
revision = '40a8e554796c'
down_revision = 'e1e967f56f02'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGroupsToRoles',
    sa.Column('user_group_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('role_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['UserGroups.group_id'], )
    )
    op.create_table('UsersToUserGroups',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('user_group_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['UserGroups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersToUserGroups')
    op.drop_table('UserGroupsToRoles')
    ### end Alembic commands ###
