"""Set HueBridge Name and Address to be unique

Revision ID: ae4b47874d73
Revises: efb623fa576b
Create Date: 2016-11-27 12:26:09.658966

"""

# revision identifiers, used by Alembic.
revision = 'ae4b47874d73'
down_revision = 'efb623fa576b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('HueBridges', 'name', type_=sa.VARCHAR(150), existing_type=sa.VARCHAR(255))
    op.execute("ALTER TABLE HueBridges ADD CONSTRAINT un_name UNIQUE(name)")
    op.execute("ALTER TABLE HueBridges ADD CONSTRAINT un_address UNIQUE(address)")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE HueBridges DROP INDEX un_name")
    op.execute("ALTER TABLE HueBridges DROP INDEX un_address")
    op.alter_column('HueBridges', 'name', type_=sa.VARCHAR(255), existing_type=sa.VARCHAR(150))
    ### end Alembic commands ###
