"""Create inital db

Revision ID: d8775b83dabd
Revises: 
Create Date: 2016-11-12 11:10:30.533577

"""

# revision identifiers, used by Alembic.
revision = 'd8775b83dabd'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Users_time'), 'Users', ['time'], unique=False)
    op.create_index(op.f('ix_Users_timestamp'), 'Users', ['timestamp'], unique=False)
    op.create_table('APIKeys',
    sa.Column('api_key_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=36), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('api_key_id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index(op.f('ix_APIKeys_created'), 'APIKeys', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_APIKeys_created'), table_name='APIKeys')
    op.drop_table('APIKeys')
    op.drop_index(op.f('ix_Users_timestamp'), table_name='Users')
    op.drop_index(op.f('ix_Users_time'), table_name='Users')
    op.drop_table('Users')
    ### end Alembic commands ###
