"""Add in Users and Group tables

Revision ID: e1e967f56f02
Revises: d8775b83dabd
Create Date: 2016-11-12 11:56:20.818016

"""

# revision identifiers, used by Alembic.
revision = 'e1e967f56f02'
down_revision = 'd8775b83dabd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('role_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserGroups',
    sa.Column('group_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserGroups')
    op.drop_table('Roles')
    ### end Alembic commands ###
